############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "For You"
url = "/you"
weight = 2

[[main]]
name = "For Policymakers"
url = "/policymakers"
weight = 3

[[main]]
name = "For Academics"
url = "/academics"
weight = 4

[[main]]
name = "News"
url = "/news"
weight = 5

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1
