############# English navigation ##############

[[main]]
name = "For Policymakers"
url = "/policymakers"
weight = 3

[[main]]
name = "For Academics"
url = "/academics"
weight = 4

[[main]]
name = "News"
url = "/news"
weight = 5


[[main]]
name = "Members"
url = "/members"
weight = 6

# footer menu
[[footer]]
name = "Members"
url = "/members"
weight = 1
